name = "RFFGradientMatching"
uuid = "a1462534-b820-4bae-8d7a-6edb4ef569c0"
authors = ["Shuichi Miyazawa"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
